### ISSUE TITLE
contribute to AUR

### ISSUE THREAD

**Issue by azrdev** [mratsim/Arch-Machine-Learning#5]
Excuse me if I overlooked it, but you don't state why you don't upload these PKGBUILDs into the AUR (actually, those that aren't already available, like `mlxtend`).

Would you mind doing so?

**Comment by mratsim** [comment]
It's mostly because those packages are on my server which has the following setup:

- Debian host with Nvidia driver built from source
- Arch LXC container following the Debian host Nvidia driver version

Meaning I don't update Cuda, CuDNN, Nvidia-utils as often as Arch upstream.

That would create maintenance issues for the packages as I don't plan to update my debian drivers too often but the Arch ecosystem will move on.

**Comment by azrdev** [comment]
@mratsim I see. If you don't mind, I'd take at least your PKGFILE for `mlxtend` and submit a current version to the AUR (with myself as maintainer), because the software is missing from arch atm.
